# Generated by Django 4.2.3 on 2023-10-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_news_image_news_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELED', 'Canceled'), ('CHECK', 'Check'), ('PAST', 'Past')], default='ACTIVE', max_length=10),
        ),
    ]
